apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vet
  name: vet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vet
  strategy: {}
  template:
    metadata:
      labels:
        app: vet
    spec:
      containers:
      - image: vetfrank/vet:v1.0.2
        name: vet
        resources: {}
status: {}
