apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vet
    argocd.argoproj.io/instance: vet
  name: vet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vet
status:
  loadBalancer: {}
